version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  frontend-web:
    build: ./frontend-web
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network


  frontend-mobile:
    build: ./frontend-mobile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    networks:
    - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: