services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: uguee_db
      DB_PORT: 5432
    depends_on:
      - db


  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uguee_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  app-web:
    build: ./app-web
    ports:
      - "3000:3000" 
    networks:
      - app-network
    restart: unless-stopped
    command: npm run start
    volumes:
      - ./app-web:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge