version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm install -g nodemon && nodemon --legacy-watch server.js"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: uguee_db
      DB_PORT: 5432
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uguee_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  app-web:
    build: ./app-web
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./app-web:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge